//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O3DRender {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O3DRender.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float4x4 World;
        ///float4x4 ViewProj;
        ///float4 Color = float4(1,1,1,1);
        ///
        ///struct VS_IN
        ///{
        ///	float3 position : POSITION;
        ///	float3 normal : NORMAL;
        ///	float2 uv : TEXCOORD;
        ///	float4 color : COLOR;
        ///};
        ///
        ///struct PS_IN
        ///{
        ///	float4 position : POSITION;
        ///	float3 normal : TEXCOORD0;
        ///	float2 uv : TEXCOORD1;
        ///	float4 color : TEXCOORD2;
        ///};
        ///
        ///PS_IN VS(VS_IN input)
        ///{
        ///	PS_IN output = (PS_IN)0;
        ///	float4 wpos = mul(float4(input.position,1), World);
        ///	output.position = mul(wpos, ViewProj);
        ///	output.normal = normalize(mul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shader {
            get {
                return ResourceManager.GetString("Shader", resourceCulture);
            }
        }
    }
}
